---
ID: "db2c734c-0b58-4bc6-9efd-714e997d0cd8"
Parent: "beaba954-4d04-439c-aad4-e505a379557b"
Template: "beaba954-4d04-439c-aad4-e505a379557b"
Path: /sitecore/templates/Project/Sitecore_Internal/Common/Tabs/Panel/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231111T233157Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "da63f621-38bd-4389-99f7-8ede77dfa530"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231111T233157Z
