---
ID: "ceb4b67e-ee09-4b70-b74d-2d4f335c517f"
Parent: "8d226b16-a78d-43cd-a81f-76f77145bda7"
Template: "8d226b16-a78d-43cd-a81f-76f77145bda7"
Path: /sitecore/templates/Project/Sitecore_Internal/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {8D226B16-A78D-43CD-A81F-76F77145BDA7}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230826T024249Z
    - ID: "2d485833-d4a0-4ad0-9705-945892fc7ab2"
      Hint: Title
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "00eff541-fecb-48f6-940b-71709e4dd9ca"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230826T024252Z
