---
ID: "fea3dc64-2d01-4887-9a12-99fd2c461ce9"
Parent: "5c45790f-2806-428f-a292-5f13d463ccba"
Template: "5c45790f-2806-428f-a292-5f13d463ccba"
Path: /sitecore/templates/Project/Sitecore_Internal/DataSource/Tabs Container/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {5C45790F-2806-428F-A292-5F13D463CCBA}
    {FB25D85D-6FF8-44CF-A15C-7398846231A3}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231111T233717Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "38adcc18-4dce-4254-9c1a-446c30cc415e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231111T233930Z
