---
ID: "4805afde-4b45-4677-9bf1-1d6de9ca1a2a"
Parent: "a602c9a6-15a6-4bd4-93fd-5b7fb54b050d"
Template: "a602c9a6-15a6-4bd4-93fd-5b7fb54b050d"
Path: /sitecore/templates/Project/Sitecore_Internal/Common/ParameterTemplate/AppNavigationParameter/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231110T002536Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d64c5a28-8c73-4ac7-a059-dd8fab6e23de"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231110T002536Z
