---
ID: "d7d8d632-4dae-4455-8611-641023c15bb2"
Parent: "d3a4d3e6-a4dd-41ad-97b0-737195b92f06"
Template: "d3a4d3e6-a4dd-41ad-97b0-737195b92f06"
Path: /sitecore/templates/Project/Sitecore_Internal/Common/Accordian Item/Accordion Child Container/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {D3A4D3E6-A4DD-41AD-97B0-737195B92F06}
    {37F6660D-7CE9-4A89-8D20-AA8A81BDA2E8}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231114T061605Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a62bfc8b-f773-46cd-ab6b-7dcb3c939101"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231114T061850Z
