---
ID: "e4b64297-87be-44cb-9936-f26503afc9e9"
Parent: "4a2c319f-9c83-42a0-b50d-28c1add0ab05"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: "/sitecore/content/Sitecore_Internal/sitecore-dev-collection-jp/Settings/Shared Sites Settings"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230826T024441Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "603c77e9-748c-4ef4-a2b9-6bfcd1275ff6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arif.uzzaman@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230826T024441Z
